// Generated by CoffeeScript 1.6.3
(function() {
  var fs, w, _,
    _this = this;

  _ = require('underscore');

  w = require('winston');

  fs = require('fs');

  module.exports = function(configFile) {
    var loggers;
    return loggers = {};
  };

}).call(this);
